In [2]:
import pandas as pd 
import numpy as np

In [6]:
train_data = pd.read_csv('train.csv') 
test_data = pd.read_csv('test.csv')

In [7]:
train_data.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population,class
0,0,147.734256,16.959273,25.472123,21.895559,20.357926,19.257113,18.621057,0.408982,M,Red_Sequence,GALAXY
1,1,127.988677,32.346716,20.778509,19.087062,17.587208,17.226067,16.786433,0.157976,M,Red_Sequence,GALAXY
2,2,179.792648,35.344843,21.035203,21.079128,21.171840,20.582629,20.557366,2.823770,O/B,Blue_Cloud,QSO
3,3,225.818295,48.569421,23.305056,21.050736,19.017754,18.365658,17.914952,0.536099,M,Red_Sequence,GALAXY
4,4,141.836135,19.342852,21.703158,19.471680,18.234449,17.899447,17.616185,0.555761,M,Red_Sequence,GALAXY

In [8]:
test_data.head()

,id,alpha,delta,u,g,r,i,z,redshift,spectral_type,galaxy_population
0,577347,120.719779,23.924249,23.668066,21.951680,21.086183,20.180032,19.202124,0.429042,G/K,Red_Sequence
1,577348,219.414419,42.171651,24.902933,22.338822,20.732163,19.860330,19.687691,0.867305,M,Red_Sequence
2,577349,173.568731,-1.756400,19.427591,18.474633,17.551314,16.570674,16.176765,0.224234,G/K,Blue_Cloud
3,577350,184.903993,-1.411074,23.121029,21.526855,20.670159,20.417633,20.699095,0.066507,G/K,Red_Sequence
4,577351,222.487816,15.381403,25.094282,22.643981,21.123173,19.439500,19.094158,0.977218,M,Red_Sequence

In [9]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577347 entries, 0 to 577346
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 577347 non-null  int64
 1   alpha              577347 non-null  float64
 2   delta              577347 non-null  float64
 3   u                  577347 non-null  float64
 4   g                  577347 non-null  float64
 5   r                  577347 non-null  float64
 6   i                  577347 non-null  float64
 7   z                  577347 non-null  float64
 8   redshift           577347 non-null  float64
 9   spectral_type      577347 non-null  object
 10  galaxy_population  577347 non-null  object
 11  class              577347 non-null  object
dtypes: float64(8), int64(1), object(3)
memory usage: 52.9+ MB

In [10]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247435 entries, 0 to 247434
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 247435 non-null  int64
 1   alpha              247435 non-null  float64
 2   delta              247435 non-null  float64
 3   u                  247435 non-null  float64
 4   g                  247435 non-null  float64
 5   r                  247435 non-null  float64
 6   i                  247435 non-null  float64
 7   z                  247435 non-null  float64
 8   redshift           247435 non-null  float64
 9   spectral_type      247435 non-null  object
 10  galaxy_population  247435 non-null  object
dtypes: float64(8), int64(1), object(2)
memory usage: 20.8+ MB

In [11]:
train_data.isnull().sum()

id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
class                0
dtype: int64

In [12]:
test_data.isnull().sum()

id                   0
alpha                0
delta                0
u                    0
g                    0
r                    0
i                    0
z                    0
redshift             0
spectral_type        0
galaxy_population    0
dtype: int64

In [18]:
train_data.columns

Index(['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift', 'class',
       'spectral_type_A/F', 'spectral_type_G/K', 'spectral_type_M',
       'spectral_type_O/B', 'galaxy_population_Blue_Cloud',
       'galaxy_population_Red_Sequence'],
      dtype='object')

In [19]:
test_data.columns

Index(['id', 'alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift',
       'spectral_type_A/F', 'spectral_type_G/K', 'spectral_type_M',
       'spectral_type_O/B', 'galaxy_population_Blue_Cloud',
       'galaxy_population_Red_Sequence'],
      dtype='object')

In [20]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 577347 entries, 0 to 577346
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              577347 non-null  int64
 1   alpha                           577347 non-null  float64
 2   delta                           577347 non-null  float64
 3   u                               577347 non-null  float64
 4   g                               577347 non-null  float64
 5   r                               577347 non-null  float64
 6   i                               577347 non-null  float64
 7   z                               577347 non-null  float64
 8   redshift                        577347 non-null  float64
 9   class                           577347 non-null  object
 10  spectral_type_A/F               577347 non-null  bool
 11  spectral_type_G/K               577347 non-null  bool
 12  spectral_type_M                 577347 non-null  bool
 13  spectral_type_O/B               577347 non-null  bool
 14  galaxy_population_Blue_Cloud    577347 non-null  bool
 15  galaxy_population_Red_Sequence  577347 non-null  bool
dtypes: bool(6), float64(8), int64(1), object(1)
memory usage: 47.4+ MB

In [21]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247435 entries, 0 to 247434
Data columns (total 15 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              247435 non-null  int64
 1   alpha                           247435 non-null  float64
 2   delta                           247435 non-null  float64
 3   u                               247435 non-null  float64
 4   g                               247435 non-null  float64
 5   r                               247435 non-null  float64
 6   i                               247435 non-null  float64
 7   z                               247435 non-null  float64
 8   redshift                        247435 non-null  float64
 9   spectral_type_A/F               247435 non-null  bool
 10  spectral_type_G/K               247435 non-null  bool
 11  spectral_type_M                 247435 non-null  bool
 12  spectral_type_O/B               247435 non-null  bool
 13  galaxy_population_Blue_Cloud    247435 non-null  bool
 14  galaxy_population_Red_Sequence  247435 non-null  bool
dtypes: bool(6), float64(8), int64(1)
memory usage: 18.4 MB

In [26]:
# Features
X = train_data.drop(columns=['class'])

# Target
y = train_data['class']

# Test Features
X_test = test_data

In [27]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

Importing CatBoostClassifier Model

In [32]:
!pip install catboost
from catboost import CatBoostClassifier

Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-macosx_11_0_universal2.whl.metadata (1.4 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas<4.0,>=0.24 in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.13/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib->catboost) (3.2.0)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.10-cp313-cp313-macosx_11_0_universal2.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 7.5 MB/s  0:00:03m0:00:0100:01
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [catboost]1/2 [catboost]
Successfully installed catboost-1.2.10 graphviz-0.21

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

Defining Model

In [33]:


model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function='MultiClass',
    verbose=100
)

model.fit(X_train, y_train)

0:	learn: 1.0198135	total: 121ms	remaining: 2m 1s
100:	learn: 0.1455118	total: 5.52s	remaining: 49.2s
200:	learn: 0.1220342	total: 10.6s	remaining: 42s
300:	learn: 0.1122337	total: 16.1s	remaining: 37.3s
400:	learn: 0.1062092	total: 21.3s	remaining: 31.9s
500:	learn: 0.1023393	total: 26.2s	remaining: 26.1s
600:	learn: 0.0993326	total: 31.1s	remaining: 20.7s
700:	learn: 0.0968266	total: 36s	remaining: 15.4s
800:	learn: 0.0947996	total: 41s	remaining: 10.2s
900:	learn: 0.0929642	total: 45.6s	remaining: 5.01s
999:	learn: 0.0914083	total: 50.5s	remaining: 0us

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, loss_function='MultiClass', verbose=100)

Model Accuracy

In [34]:
from sklearn.metrics import accuracy_score

valid_preds = model.predict(X_valid)

print("Accuracy:", accuracy_score(y_valid, valid_preds))

Accuracy: 0.9634017493721313

Training on Full Data

In [35]:
model.fit(X, y)

0:	learn: 1.0193103	total: 82.7ms	remaining: 1m 22s
100:	learn: 0.1457633	total: 6.54s	remaining: 58.3s
200:	learn: 0.1222604	total: 14s	remaining: 55.6s
300:	learn: 0.1123063	total: 21s	remaining: 48.8s
400:	learn: 0.1066471	total: 28s	remaining: 41.8s
500:	learn: 0.1026607	total: 34.8s	remaining: 34.6s
600:	learn: 0.0997506	total: 41.4s	remaining: 27.5s
700:	learn: 0.0973121	total: 48.1s	remaining: 20.5s
800:	learn: 0.0954416	total: 55.3s	remaining: 13.7s
900:	learn: 0.0937893	total: 1m 2s	remaining: 6.85s
999:	learn: 0.0923683	total: 1m 9s	remaining: 0us

CatBoostClassifier(depth=8, iterations=1000, learning_rate=0.05, loss_function='MultiClass', verbose=100)

In [ ]:
final_prediction = model.predict(X_test)
final_prediction = le.inverse_transform(final_prediction)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/preprocessing/_label.py:151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array(['GALAXY', 'GALAXY', 'GALAXY', ..., 'GALAXY', 'QSO', 'GALAXY'],
      dtype=object)

In [38]:
submission  = pd.DataFrame({
    'id': test_data['id'],
    'class': final_prediction
})

In [39]:
submission

            id   class
0       577347  GALAXY
1       577348  GALAXY
2       577349  GALAXY
3       577350    STAR
4       577351  GALAXY
...        ...     ...
247430  824777     QSO
247431  824778     QSO
247432  824779  GALAXY
247433  824780     QSO
247434  824781  GALAXY

[247435 rows x 2 columns]

In [40]:
submission.to_csv('submission.csv', index=False)